#!/bin/bash

cat <<EOF
  LV          VG      Attr       LSize         Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool vg_root twi-a-t---  46082818048B             0.13   0.02
  lv_fs       vg_root -wi-ao---- 463235710976B
  lv_log      vg_root -wi-ao----   4294967296B
  lv_root     vg_root -wi-ao----  10737418240B
  lv_swap     vg_root -wi-ao----   4294967296B
EOF
